version: '3'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile-Jenkins
    image: DinD/jenkins-local:3.7.0
    ports:
      - "8081:8080"
    volumes:
      - /var/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.version:/var/jenkins_home/.version
    container_name: jenkins-svr
    restart: always
    networks: 
      - net
  # jenkins-socat:
  #   container_name: jenkins-socat
  #   image: alpine/socat
  #   command: "tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock"
  #   networks: 
  #     - net
  #   restart: always
  #   ports:
  #     - "127.0.0.1:2375:2375"
  version-control:
    build:
      context: .
      dockerfile: Dockerfile-version-controller  # Certifique-se de que o Dockerfile está no diretório correto
    image: DinD/version-control:3.7.0
    ports:
      - "4004:4005"
    volumes:
      - ./.version:/app/.version
    container_name: jenkins-version
    restart: unless-stopped
    networks: 
      - net
  sonarqube-db:
    image: postgres
    container_name: sonarqube-db
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
    volumes:
      - ./postgre_volume:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - net
  sonarqube-main:
    image: sonarqube:community
    container_name: sonarqube-svr
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://sonarqube-db:5432/sonarqube
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    depends_on:
      - sonarqube-db
    networks:
      - net
networks:
  net:
    driver: bridge
